# Yellow Labs
## Combining dog breed and intelligence data
### Lauren, Abigail, Brennan

In [1]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine

# Data Extraction

## Extract dog intelligence data from a csv and create a dataframe

In [2]:
csv_file = "dog_intelligence.csv"
intelligence_df = pd.read_csv(csv_file)
intelligence_df.sort_values("Breed").head(5)

,Breed,Classification,obey,reps_lower,reps_upper
53,Affenpinscher,Above Average Working Dogs,70%,16,25
135,Afghan Hound,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
36,Airedale Terrier,Above Average Working Dogs,70%,16,25
102,Akita,Average Working/Obedience Intelligence,50%,26,40
93,Alaskan Malamute,Average Working/Obedience Intelligence,50%,26,40

## Extract dog breed data from a csv and create a dataframe

In [3]:
csv_file = "akc_breed_info.csv"
breed_df = pd.read_csv(csv_file, encoding='ISO-8859-1')
breed_df.tail()

,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs
145,Papillon,8,11,5,10
146,Pomeranian,12,12,3,7
147,Poodle Toy,10,10,10,10
148,Toy Fox Terrier,10,10,4,7
149,Yorkshire Terrier,8,8,3,7

# Data Transformation

## Merge the breed and intelligence dataframes on "Breed"

In [4]:
combined_df = pd.merge(breed_df, intelligence_df, on="Breed")
combined_df.tail(5)

,Breed,height_low_inches,height_high_inches,weight_low_lbs,weight_high_lbs,Classification,obey,reps_lower,reps_upper
100,Japanese Chin,8,11,4,11,Fair Working/Obedience Intelligence,30%,41,80
101,Maltese,8,10,4,6,Fair Working/Obedience Intelligence,30%,41,80
102,Papillon,8,11,5,10,Brightest Dogs,95%,1,4
103,Pomeranian,12,12,3,7,Excellent Working Dogs,85%,5,15
104,Yorkshire Terrier,8,8,3,7,Above Average Working Dogs,70%,16,25

## Rename column headers

In [14]:
renamed_df = combined_df.rename(columns={'height_low_inches':'Min_Height_(In)',
                          'height_high_inches':'Max_Height_(In)',
                          'weight_low_lbs':'Min_Weight_(lbs)',
                                 'weight_high_lbs':'Max_Weight_(lbs)',
                                 'Classification':'Intelligence_Classification',
                                 'obey':'Successful_Initial_Response_Rate',
                                 'reps_lower':'Min_Reps_to_Understanding',
                                 'reps_upper':'Max_Reps_to_Understanding'},
                 inplace=False)
renamed_df.head(20)

,Breed,Min_Height_(In),Max_Height_(In),Min_Weight_(lbs),Max_Weight_(lbs),Intelligence_Classification,Successful_Initial_Response_Rate,Min_Reps_to_Understanding,Max_Reps_to_Understanding
0,Akita,26,28,80,120,Average Working/Obedience Intelligence,50%,26,40
1,Bernese Mountain Dog,23,27,85,110,Excellent Working Dogs,85%,5,15
2,Bloodhound,24,26,80,120,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
3,Borzoi,26,28,70,100,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
4,Bullmastiff,25,27,100,130,Fair Working/Obedience Intelligence,30%,41,80
5,Great Dane,32,32,120,160,Average Working/Obedience Intelligence,50%,26,40
6,Great Pyrenees,27,32,95,120,Fair Working/Obedience Intelligence,30%,41,80
7,Irish Wolfhound,28,35,90,150,Average Working/Obedience Intelligence,50%,26,40
8,Kuvasz,28,30,70,120,Average Working/Obedience Intelligence,50%,26,40
9,Mastiff,27,30,175,190,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
10,Newfoundland,26,28,100,150,Above Average Working Dogs,70%,16,25
11,Rottweiler,22,27,90,110,Brightest Dogs,95%,1,4
12,Saint Bernard,25,28,110,190,Fair Working/Obedience Intelligence,30%,41,80
13,Afghan Hound,25,27,50,60,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
14,Alaskan Malamute,na,na,na,na,Average Working/Obedience Intelligence,50%,26,40
15,American Foxhound,22,25,65,70,Average Working/Obedience Intelligence,50%,26,40
16,Belgian Malinois,22,26,60,65,Excellent Working Dogs,85%,5,15
17,Belgian Sheepdog,22,26,60,75,Excellent Working Dogs,85%,5,15
18,Boxer,21,25,65,70,Average Working/Obedience Intelligence,50%,26,40
19,Briard,23,27,74,76,Above Average Working Dogs,70%,16,25

## Converted numerical columns into float datatypes for further analysis

In [16]:
renamed_df["Min_Height_(In)"] = pd.to_numeric(renamed_df["Min_Height_(In)"], errors='coerce')
renamed_df["Max_Height_(In)"] = pd.to_numeric(renamed_df["Max_Height_(In)"], errors='coerce')
renamed_df["Min_Weight_(lbs)"] = pd.to_numeric(renamed_df["Min_Weight_(lbs)"], errors='coerce')
renamed_df["Max_Weight_(lbs)"] = pd.to_numeric(renamed_df["Max_Weight_(lbs)"], errors='coerce')

In [17]:
renamed_df.head()

,Breed,Min_Height_(In),Max_Height_(In),Min_Weight_(lbs),Max_Weight_(lbs),Intelligence_Classification,Successful_Initial_Response_Rate,Min_Reps_to_Understanding,Max_Reps_to_Understanding
0,Akita,26.0,28.0,80.0,120.0,Average Working/Obedience Intelligence,50%,26,40
1,Bernese Mountain Dog,23.0,27.0,85.0,110.0,Excellent Working Dogs,85%,5,15
2,Bloodhound,24.0,26.0,80.0,120.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
3,Borzoi,26.0,28.0,70.0,100.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100
4,Bullmastiff,25.0,27.0,100.0,130.0,Fair Working/Obedience Intelligence,30%,41,80

## Aggregate the height, weight, and repitition columns to get the average and insert those columns into the dataframe

In [18]:
renamed_df.insert(3, "Avg_Height_(In)", ((renamed_df["Min_Height_(In)"] + renamed_df["Max_Height_(In)"])/2), True)
renamed_df.insert(6, "Avg_Weight_(lbs)", ((renamed_df["Min_Weight_(lbs)"] + renamed_df["Max_Weight_(lbs)"])/2), True)
renamed_df.insert(11, "Avg_Reps_to_Understanding", ((renamed_df["Min_Reps_to_Understanding"] + renamed_df["Max_Reps_to_Understanding"])/2), True)
renamed_df.head()

,Breed,Min_Height_(In),Max_Height_(In),Avg_Height_(In),Min_Weight_(lbs),Max_Weight_(lbs),Avg_Weight_(lbs),Intelligence_Classification,Successful_Initial_Response_Rate,Min_Reps_to_Understanding,Max_Reps_to_Understanding,Avg_Reps_to_Understanding
0,Akita,26.0,28.0,27.0,80.0,120.0,100.0,Average Working/Obedience Intelligence,50%,26,40,33.0
1,Bernese Mountain Dog,23.0,27.0,25.0,85.0,110.0,97.5,Excellent Working Dogs,85%,5,15,10.0
2,Bloodhound,24.0,26.0,25.0,80.0,120.0,100.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,90.5
3,Borzoi,26.0,28.0,27.0,70.0,100.0,85.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,90.5
4,Bullmastiff,25.0,27.0,26.0,100.0,130.0,115.0,Fair Working/Obedience Intelligence,30%,41,80,60.5

## Set the dataframe index to "Breed"

In [19]:
renamed_df.set_index("Breed").head()

,Min_Height_(In),Max_Height_(In),Avg_Height_(In),Min_Weight_(lbs),Max_Weight_(lbs),Avg_Weight_(lbs),Intelligence_Classification,Successful_Initial_Response_Rate,Min_Reps_to_Understanding,Max_Reps_to_Understanding,Avg_Reps_to_Understanding
Breed,,,,,,,,,,,
Akita,26.0,28.0,27.0,80.0,120.0,100.0,Average Working/Obedience Intelligence,50%,26,40,33.0
Bernese Mountain Dog,23.0,27.0,25.0,85.0,110.0,97.5,Excellent Working Dogs,85%,5,15,10.0
Bloodhound,24.0,26.0,25.0,80.0,120.0,100.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,90.5
Borzoi,26.0,28.0,27.0,70.0,100.0,85.0,Lowest Degree of Working/Obedience Intelligence,NaN,81,100,90.5
Bullmastiff,25.0,27.0,26.0,100.0,130.0,115.0,Fair Working/Obedience Intelligence,30%,41,80,60.5

# Loading the Data into a MySQL Database
* We chose MySQL because our data was tabular, and we didn't require flexibility in our data's structure

## Create a New MySQL Database

In [22]:
create_engine('mysql://root:LaurensMySQL11@localhost').execute('CREATE DATABASE IF NOT EXISTS labs_db')

## Connect to our new MySQL database

In [23]:
rds_connection_string = "root:LaurensMySQL11@127.0.0.1/labs_db"
engine = create_engine(f'mysql://{rds_connection_string}')

## Load our table of dogs into our new database

In [24]:
renamed_df.to_sql(name='labs_data', con=engine, if_exists='fail', index=False)

## Confirm the data was loaded into the database by querying it

In [25]:
pd.read_sql_query('select * from labs_data', con=engine).head()

,Breed,Min_Height_(In),Max_Height_(In),Avg_Height_(In),Min_Weight_(lbs),Max_Weight_(lbs),Avg_Weight_(lbs),Intelligence_Classification,Successful_Initial_Response_Rate,Min_Reps_to_Understanding,Max_Reps_to_Understanding,Avg_Reps_to_Understanding
0,Akita,26.0,28.0,27.0,80.0,120.0,100.0,Average Working/Obedience Intelligence,50%,26,40,33.0
1,Bernese Mountain Dog,23.0,27.0,25.0,85.0,110.0,97.5,Excellent Working Dogs,85%,5,15,10.0
2,Bloodhound,24.0,26.0,25.0,80.0,120.0,100.0,Lowest Degree of Working/Obedience Intelligence,None,81,100,90.5
3,Borzoi,26.0,28.0,27.0,70.0,100.0,85.0,Lowest Degree of Working/Obedience Intelligence,None,81,100,90.5
4,Bullmastiff,25.0,27.0,26.0,100.0,130.0,115.0,Fair Working/Obedience Intelligence,30%,41,80,60.5